### ISSUE TITLE
Improving the home page look and feel

### ISSUE THREAD

**Issue by Tilliforkids** [tillioss/tilli-web-app#12]
This screen needs to be redesigned with the new art assets and style M1 is following. 
- Need to update the iconography 
- Need to adjust the content

<img width="300" alt="image" src="https://user-images.githubusercontent.com/119949642/206436129-75c5cfb1-be30-4642-b37a-3a84855ce2f1.png">

**Comment by Briandsouza-17** [comment]
Updated
