### ISSUE TITLE
Improve the code formatting of the dropdown component

### ISSUE THREAD

**Issue by anjula-sack** [tillioss/tilli-web-app#42]
**Is your feature request related to a problem? Please describe.**
* Currently, the dropdown component is formatted properly.

**Describe the solution you'd like**

Improve the formatting of the dropdown component.

1. Go to `src/Component/DropDown.js`
2. Paste the following code 

```
import Select from "react-select";

const DropDown = (props) => {
  return (
    <Select
      value={props.selectedOption}
      onChange={props.onChange}
      options={props.options}
    />
  );
};
export default DropDown;
```
3. Send a pull request with the changes

**Comment by Sanjana0319** [comment]
I would like to worn on this.
