### ISSUE TITLE
Remove the commented custom styles code from the dropdown

### ISSUE THREAD

**Issue by anjula-sack** [tillioss/tilli-web-app#43]
**Is your feature request related to a problem? Please describe.**
* Currently, There are commented-out code snippets in some components

**Describe the solution you'd like**
1. Go to `src/Component/TilliGameWebDropDown.js`
2. Remove the following code
```
  // const customStyles = () => ({
  //   control: (styles) => ({
  //     ...styles,
  //     background: "red",
  //     backgroundColor: "red",
  //   }),
  //   menu: (base) => ({
  //     ...base,
  //     background: "#FFF",
  //     color: "#000",
  //     backgroundColor: "red",
  //   }),
  //   option: (provided, state) => ({
  //     ...provided,
  //     color: 'black',
  //     backgroundColor: state.isSelected ? "rgba(189,197,209,.3)" : "white",
  //   }),
  //   singleValue: provided => ({
  //     ...provided,
  //     height: '100%',
  //     color: '#08699B',
  //     paddingTop: '3px',
  //   }),
  // });
```
3. Sent a pull request with the relevant changes

**Comment by Preetraj2002** [comment]
Please assign me this task. I would be really like to work on it

**Comment by anjula-sack** [comment]
> Please assign me this task. I would be really like to work on it

Go ahead @Preetraj2002

**Comment by Parvej2001** [comment]
@Preetraj2002 can we collaborate on this task or u have completed ?
