### ISSUE TITLE
Remove the commented-out code snippets from the dashboard component

### ISSUE THREAD

**Issue by anjula-sack** [tillioss/tilli-web-app#44]
**Is your feature request related to a problem? Please describe.**
* Currently, There are commented-out code snippets in some components

**Describe the solution you'd like**
1. Go to `src/Screens/Dashbord_1.js`
2. Remove the following code lines
```
// this.props.setUserInfo('progressingLevel', 0)
//this.props.setUserInfo('progressingLevel', JSON.parse(responseData.response).level)
//console.log('json level',json)
// console.log('val', this.state.bodydata[val])
// console.log(this.state.bodydata[val].id)
//MyConstant.keyList.projectUrl + "/module/?:id
```
3. Sent a pull request with the relevant changes

**Comment by Preetraj2002** [comment]
Please assign me this task. I would love to work on it
