### ISSUE TITLE
Remove the commented-out code snippets from the common config

### ISSUE THREAD

**Issue by anjula-sack** [tillioss/tilli-web-app#51]
**Is your feature request related to a problem? Please describe.**
* Currently, There are commented-out code snippets in some components

**Describe the solution you'd like**
1. Go to `src/config/Common.js`
2. Remove the  code lines that are commented
3. Sent a pull request with the relevant changes

**Comment by Preetraj2002** [comment]
Please assign me this task. I would love to work on it
