### ISSUE TITLE
Remove the commented-out code snippets in the AudioQuizScreen.js

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#57]
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

        1. Go to `src\Component\Themes\AudioQuizScreen.js`
        2. Remove the code lines that are commented
        3. Send a pull request with the changes

**Comment by Preetraj2002** [comment]
assign me task i would love to contribute @Sanjana0319

**Comment by anjula-sack** [comment]
@Preetraj2002 Are you working on this?

**Comment by Preetraj2002** [comment]
Sorry for the delay I had classes and needed to commute. Will fix this ASAP

**Comment by anjula-sack** [comment]
> Sorry for the delay I had classes and needed to commute. Will fix this ASAP

No worries, take your time! :)
