### ISSUE TITLE
Remove commented lines ChooseCheckboxQuestions.js

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#59]
**Is your feature request related to a problem? Please describe.**

- Currently, the ChooseCheckboxQuestions file has commented lines.

**Describe the solution you'd like**

    1. Go to src\Component\Themes\ChooseCheckboxQuestions.js
    2. Remove all commented lines.
    3. Send a pull request with the changes

**Comment by Preetraj2002** [comment]
Ooh it's already assigned no prob @Sanjana0319 could take care of it

**Comment by Sanjana0319** [comment]
Since you have a few issues already assigned you can finish them before getting assigned more :)
