### ISSUE TITLE
Remove the commented-out code snippets in the CircleWithInfoAnimations.js

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#65]
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

1. Go to `src\Component\Themes\CircleWithInfoAnimations.js`
2. Remove the code lines that are commented
3. Send a pull request with the changes

**Comment by anjula-sack** [comment]
https://github.com/tillioss/tilli-web-app/pull/104
