### ISSUE TITLE
Remove the commented-out code snippets in the DropToSelectionNew.js

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#68]
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

1. Go to `src\Component\Themes\DropToSelectionNew.js`
2. Remove the code lines that are commented
3. Send a pull request with the changes

**Comment by KunalBhat55** [comment]
Hey I would like to work on this, can you assign it to me?

**Comment by anjula-sack** [comment]
> Hey I would like to work on this, can you assign it to me?

Sure, Go ahead
