### ISSUE TITLE
Remove the commented-out code snippets in the StoryCardScreen.js

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#72]
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

1. Go to `src\Component\Themes\StoryCardScreen.js`
2. Remove the code lines that are commented
3. Sent a pull request with the relevant changes

**Comment by Rahul-jain-01** [comment]
Hey, can you please assign it to me
Thank you.

**Comment by anjula-sack** [comment]
> Hey, can you please assign it to me Thank you.

Go ahead @Rahul-jain-01

**Comment by Rahul-jain-01** [comment]
I have completed it
Can you checkout the PR
Thank you.
