### ISSUE TITLE
Remove the commented-out code snippets in the Success.js

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#73]
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

1. Go to `src\Component\Themes\Success.js`
2. Remove the code lines that are commented
3. Sent a pull request with the relevant changes

**Comment by anjula-sack** [comment]
Hi @habib33-3, Please make sure that the issue is assigned for you before making a pull request.
