### ISSUE TITLE
Remove the commented-out code snippets in the HomeScreen.js

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#77]
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

1. Go to `src\pages\HomeScreen.js`
2. Remove the code lines that are commented
3. Sent a pull request with the relevant changes

**Comment by antriksh-9** [comment]
Hey @Sanjana0319 I want to work on this issue.
Please assign it to me.

**Comment by anjula-sack** [comment]
> Hey @Sanjana0319 I want to work on this issue. Please assign it to me.

Go ahead @antriksh-9
