### ISSUE TITLE
Remove the commented-out code snippets in the ModuleScreen.js

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#78]
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

1. Go to `src\pages\ModuleScreen.js`
2. Remove the code lines that are commented
3. Sent a pull request with the relevant changes

**Comment by Ahnaf-codes** [comment]
@Sanjana0319 assign me

**Comment by anjula-sack** [comment]
> @anjula-sack assign me

Can you send PR for the assigned issues first before getting assigned for more?

**Comment by KunalBhat55** [comment]
Hey I would like to work on this, can you assign it to me?

**Comment by anjula-sack** [comment]
> Hey I would like to work on this, can you assign it to me?

Go ahead @KunalBhat55
