### ISSUE TITLE
Remove the commented-out code snippets in the TilliGameWeb.js

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#79]
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

1. Go to `src\pages\TilliGameWeb.js`
2. Remove the code lines that are commented
3. Sent a pull request with the relevant changes

**Comment by Keshav-Aneja** [comment]
Can i work on this issue?

**Comment by anjula-sack** [comment]
> Can i work on this issue?

Go ahead @Keshav-Aneja
