### ISSUE TITLE
Remove the commented-out code snippets in the TrackProgressScreen.js

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#80]
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

1. Go to `src\pages\TrackProgressScreen.js`
2. Remove the code lines that are commented
3. Sent a pull request with the relevant changes

**Comment by anjula-sack** [comment]
Hi @Ahnaf-codes, There are 2 issues already assigned for you. Can you work on them before getting assigned for more?

**Comment by KunalBhat55** [comment]
Hey I would like to work on this, Can you assign me or should I directly make a PR

**Comment by anjula-sack** [comment]
> Hey I would like to work on this, Can you assign me or should I directly make a PR

Hi @KunalBhat55, There's a pending PR for this. You can work on another issue.

**Comment by KunalBhat55** [comment]
> > Hey I would like to work on this, Can you assign me or should I directly make a PR
> 
> Hi @KunalBhat55, There's a pending PR for this. You can work on another issue.

I have commented on other issues could you please check that out!
