### ISSUE TITLE
Remove the commented-out code snippets

### ISSUE THREAD

**Issue by Sanjana0319** [tillioss/tilli-web-app#82]
**Is your feature request related to a problem? Please describe.**

- Currently, There are commented-out code snippets in some components.

**Describe the solution you'd like**

1. Go to `src\redux\store\index.js`
2. Remove the code lines that are commented
3. Sent a pull request with the relevant changes

**Comment by Ahnaf-codes** [comment]
@Sanjana0319 i can do this. please assign me

**Comment by anjula-sack** [comment]
> @Sanjana0319 i can do this. please assign me

Go ahead!
